apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-reverse-proxy-service
  name: udagram-reverse-proxy-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-reverse-proxy
  type: LoadBalancer